
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ancho = 9;
  public static final int utemp = 13;
  public static final int end = 11;
  public static final int coma = 16;
  public static final int parentc = 19;
  public static final int numero = 2;
  public static final int parenta = 18;
  public static final int llave_c = 15;
  public static final int alto = 8;
  public static final int llave_a = 14;
  public static final int time = 7;
  public static final int inicio = 10;
  public static final int ident = 4;
  public static final int EOF = 0;
  public static final int vida = 6;
  public static final int error = 1;
  public static final int damage = 3;
  public static final int monedas = 12;
  public static final int enemigos = 5;
  public static final int punto_coma = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "numero",
  "damage",
  "ident",
  "enemigos",
  "vida",
  "time",
  "alto",
  "ancho",
  "inicio",
  "end",
  "monedas",
  "utemp",
  "llave_a",
  "llave_c",
  "coma",
  "punto_coma",
  "parenta",
  "parentc"
  };
}

